import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google"
// Import Geist Mono
const geistMono = Geist_Mono({
  subsets: ['latin'],
  weight: ['400', '900'],
  style: ['normal'],
});

const geist = Geist({
  subsets: ['latin'],
  weight: ['400', '900'],
  style: ['normal'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} ${geistMono.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
